import './globals.css'
import type { Metadata } from 'next' 
 

export const metadata: Metadata = {
  title: 'Nathaniel | Nextjs Exam',
  description: 'Generated by create next app - app router',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
